#!/usr/bin/env python3

"""
First-run initialization for REF.

Generates the ``settings.yaml`` configuration file with cryptographically
secure secrets, renders ``settings.env`` (consumed by docker-compose) from it,
generates ``docker-compose.yml`` from its template, and creates the container
SSH host keys used by the SSH reverse proxy.

This script must be run once before the first ``./ctrl.sh up``. It refuses to
run if ``settings.yaml`` already exists so that existing secrets are never
overwritten silently.
"""

import secrets
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict

import jinja2
import yaml

REPO_ROOT = Path(__file__).resolve().parent
SETTINGS_YAML = REPO_ROOT / "settings.yaml"
SETTINGS_ENV = REPO_ROOT / "settings.env"
COMPOSE_TEMPLATE = "docker-compose.template.yml"
COMPOSE_OUT = REPO_ROOT / "docker-compose.yml"
CONTAINER_KEYS_DIR = REPO_ROOT / "container-keys"
DOCKER_BASE_KEYS_DIR = REPO_ROOT / "ref-docker-base" / "container-keys"

SECRET_BYTES = 32


def detect_docker_group_id() -> int:
    """Look up the host's docker group ID; fall back to 999 if unavailable."""
    try:
        out = subprocess.check_output(["getent", "group", "docker"], text=True).strip()
        # Format: docker:x:<gid>:<members>
        return int(out.split(":")[2])
    except (subprocess.CalledProcessError, FileNotFoundError, IndexError, ValueError):
        return 999


def build_default_settings() -> Dict[str, Any]:
    """Assemble a fresh settings dict with cryptographically secure secrets."""
    return {
        "debug": False,
        "maintenance_enabled": False,
        "docker_group_id": detect_docker_group_id(),
        "ports": {
            "ssh_host_port": 2222,
            "http_host_port": 8000,
        },
        "admin": {
            # Auto-generated on first boot. The user logs in with username "0".
            "password": secrets.token_urlsafe(SECRET_BYTES),
            # If null, the web app generates a keypair on first boot and
            # exposes the private key via the admin web interface.
            "ssh_key": None,
        },
        "secrets": {
            # Flask session / CSRF signing key.
            "secret_key": secrets.token_urlsafe(SECRET_BYTES),
            # HMAC key shared between the SSH reverse proxy and the web API.
            "ssh_to_web_key": secrets.token_urlsafe(SECRET_BYTES),
            # PostgreSQL superuser password used for initial DB setup.
            "postgres_password": secrets.token_urlsafe(SECRET_BYTES),
        },
    }


SETTINGS_YAML_HEADER = """\
# REF configuration file.
#
# Generated by prepare.py. All secrets were created with a cryptographically
# secure random generator (Python's `secrets` module). Treat this file as
# sensitive: it grants full administrative access to the REF instance.
#
# To regenerate from scratch, delete this file together with settings.env and
# re-run ./prepare.py.
"""


def write_settings_yaml(settings: Dict[str, Any]) -> None:
    with SETTINGS_YAML.open("w") as f:
        f.write(SETTINGS_YAML_HEADER)
        yaml.safe_dump(settings, f, sort_keys=False, default_flow_style=False)
    SETTINGS_YAML.chmod(0o600)


def _env_value(value: Any) -> str:
    """Render a Python value as an env-file scalar."""
    if value is None or value is False:
        return ""
    if value is True:
        return "1"
    return str(value)


def render_settings_env(settings: Dict[str, Any]) -> None:
    """Write settings.env so that docker-compose can consume the values."""
    admin_password = settings["admin"]["password"]
    admin_ssh_key = settings["admin"]["ssh_key"] or ""
    lines = [
        "# Auto-generated by prepare.py from settings.yaml. Do not edit by hand.",
        "# Edit settings.yaml instead and re-render via ./prepare.py (after",
        "# deleting settings.yaml if you want fresh secrets).",
        "",
        f"DEBUG={1 if settings['debug'] else 0}",
        f"MAINTENANCE_ENABLED={1 if settings['maintenance_enabled'] else 0}",
        "",
        f"ADMIN_PASSWORD={admin_password}",
        f'ADMIN_SSH_KEY="{admin_ssh_key}"',
        "",
        f"DOCKER_GROUP_ID={settings['docker_group_id']}",
        "",
        f"SSH_HOST_PORT={settings['ports']['ssh_host_port']}",
        f"HTTP_HOST_PORT={settings['ports']['http_host_port']}",
        "",
        f"SECRET_KEY={settings['secrets']['secret_key']}",
        f"SSH_TO_WEB_KEY={settings['secrets']['ssh_to_web_key']}",
        f"POSTGRES_PASSWORD={settings['secrets']['postgres_password']}",
        "",
    ]
    SETTINGS_ENV.write_text("\n".join(lines))
    SETTINGS_ENV.chmod(0o600)


def generate_docker_compose() -> None:
    template_loader = jinja2.FileSystemLoader(searchpath=str(REPO_ROOT))
    template_env = jinja2.Environment(loader=template_loader)
    template = template_env.get_template(COMPOSE_TEMPLATE)

    cgroup_base = "ref"
    cgroup_parent = f"{cgroup_base}-core.slice"
    instances_cgroup_parent = f"{cgroup_base}-instances.slice"

    render_out = template.render(
        testing=False,
        bridge_id="",
        data_path="./data",
        exercises_path="./exercises",
        cgroup_parent=cgroup_parent,
        instances_cgroup_parent=instances_cgroup_parent,
        binfmt_support=False,
    )
    COMPOSE_OUT.write_text(render_out)


def generate_ssh_keys() -> None:
    """Generate the SSH host keys used by the SSH reverse proxy."""
    CONTAINER_KEYS_DIR.mkdir(exist_ok=True)

    for name in ("root_key", "user_key"):
        key_path = CONTAINER_KEYS_DIR / name
        if not key_path.exists():
            subprocess.check_call(
                ["ssh-keygen", "-t", "ed25519", "-N", "", "-f", str(key_path)]
            )

    shutil.copytree(CONTAINER_KEYS_DIR, DOCKER_BASE_KEYS_DIR, dirs_exist_ok=True)


def main() -> int:
    if SETTINGS_YAML.exists():
        print(
            f"error: {SETTINGS_YAML.name} already exists. Refusing to overwrite "
            "existing secrets.\n"
            "If you want to regenerate configuration from scratch, delete "
            f"{SETTINGS_YAML.name} and settings.env and re-run this script.",
            file=sys.stderr,
        )
        return 1

    settings = build_default_settings()
    write_settings_yaml(settings)
    render_settings_env(settings)
    generate_docker_compose()
    generate_ssh_keys()

    print(f"Wrote {SETTINGS_YAML.name} (0600)")
    print(f"Wrote {SETTINGS_ENV.name} (0600)")
    print(f"Wrote {COMPOSE_OUT.name}")
    print(f"Generated container SSH keys in {CONTAINER_KEYS_DIR.name}/")
    print()
    print("Admin credentials for first login:")
    print("  user:     0")
    print(f"  password: {settings['admin']['password']}")
    print()
    print("Next steps:")
    print("  ./ctrl.sh build")
    print("  ./ctrl.sh up")
    return 0


if __name__ == "__main__":
    sys.exit(main())
