#!/usr/bin/env python3
"""
This script is executed each time a studen creates a submission.
It is used to determine whether the submission works as expected or not.
"""
from pathlib import Path

from ref_utils import print_ok, print_warn, print_err, assert_is_file, run_pylint, run_mypy, contains_flag


SUCCESS = True
FAILURE = False


################################################################

SOLUTION_FILE = Path("/home/user/solution.py")
FLAG = "flag{You_just_got_your_1st_flag_WHOOP_WHOOP}"

def test_environment() -> bool:
    """
    Test whether all files that should be submitted are in place.
    """
    tests_passed = True
    print_ok('[+] Testing environment..')

    # Check whether solution.py exists
    tests_passed &= assert_is_file(SOLUTION_FILE)

    return tests_passed


def test_submission() -> bool:
    """
    Test if the submitted code successfully solves the exercise.
    """
    if not test_environment():
        return FAILURE
    print_ok('[+] Environment looks good, test passed!')
    tests_passed = True

    tests_passed &= run_mypy([SOLUTION_FILE])
    tests_passed &= run_pylint([SOLUTION_FILE])
    tests_passed &= contains_flag(FLAG, SOLUTION_FILE)

    return tests_passed


if __name__ == "__main__":
    print_ok('[+] Running tests..')
    if not test_submission():
        print_err('[!] Some tests failed! Please review your submission to avoid penalties during grading.')
        exit(2)
    else:
        print_ok('[+] All tests passed! Good job :) Ready to submit!')
        exit(0)
