"""empty message

Revision ID: 2676b26732cb
Revises: 3f9e41203c59
Create Date: 2019-11-27 21:10:19.622881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2676b26732cb'
down_revision = '3f9e41203c59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login_token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'login_token')
    # ### end Alembic commands ###
