"""empty message

Revision ID: 3c4183d13d38
Revises: a538def48d62
Create Date: 2019-11-10 17:44:17.691220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c4183d13d38'
down_revision = 'a538def48d62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_entry_service', sa.Column('readonly', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise_entry_service', 'readonly')
    # ### end Alembic commands ###
