"""empty message

Revision ID: 3f9e41203c59
Revises: 9f8d78b97aba
Create Date: 2019-11-25 23:29:08.312273

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f9e41203c59'
down_revision = '9f8d78b97aba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'mat_num',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'mat_num',
               existing_type=sa.BigInteger(),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
