"""empty message

Revision ID: 46f167e616ce
Revises: fd7bdab619ae
Create Date: 2021-05-07 15:57:18.486167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46f167e616ce'
down_revision = 'fd7bdab619ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['pub_key_ssh'])
    op.create_unique_constraint(None, 'user', ['priv_key'])
    op.create_unique_constraint(None, 'user', ['pub_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
