"""empty message

Revision ID: 4c71c9e8bba4
Revises: 8c05d5e66a3f
Create Date: 2025-04-30 10:25:16.285720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c71c9e8bba4'
down_revision = '8c05d5e66a3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_test_result', schema=None) as batch_op:
        batch_op.drop_constraint('submission_test_result_submission_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'submission', ['submission_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_test_result', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('submission_test_result_submission_id_fkey', 'submission', ['submission_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###
