"""empty message

Revision ID: 595d4b24fbb9
Revises: 18bf6b54afce
Create Date: 2022-11-22 14:32:54.758118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '595d4b24fbb9'
down_revision = '18bf6b54afce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_entry_service', sa.Column('no_randomize_files', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise_entry_service', 'no_randomize_files')
    # ### end Alembic commands ###
