"""empty message

Revision ID: 735c0c71d806
Revises: 819d8b54dd86
Create Date: 2020-04-24 19:46:15.481352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735c0c71d806'
down_revision = '819d8b54dd86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('exercise_service', sa.Column('health_check_cmd', sa.PickleType(), nullable=False))
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('exercise_service', 'health_check_cmd')
    # ### end Alembic commands ###
    pass