"""empty message

Revision ID: 77e32a5a4f11
Revises: 46f167e616ce
Create Date: 2021-10-29 17:21:37.467417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77e32a5a4f11'
down_revision = '46f167e616ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_pub_key_ssh_key', 'user', type_='unique')
    op.drop_column('user', 'pub_key_ssh')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pub_key_ssh', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_pub_key_ssh_key', 'user', ['pub_key_ssh'])
    # ### end Alembic commands ###
