"""empty message

Revision ID: 7ea1b14a5b23
Revises: 4207d689b420
Create Date: 2019-11-21 17:52:06.461518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea1b14a5b23'
down_revision = '4207d689b420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'instance_service', ['id', 'exercise_service_id'])
    op.create_unique_constraint(None, 'instance_service', ['id', 'instance_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instance_service', type_='unique')
    op.drop_constraint(None, 'instance_service', type_='unique')
    # ### end Alembic commands ###
