"""empty message

Revision ID: 8c05d5e66a3f
Revises: 595d4b24fbb9
Create Date: 2025-02-13 11:35:18.277724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c05d5e66a3f'
down_revision = '595d4b24fbb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission_extended_test_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.Text(), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submission_test_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.Text(), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_column('test_passed')
        batch_op.drop_column('test_output')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_output', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('test_passed', sa.BOOLEAN(), autoincrement=False, nullable=True))

    op.drop_table('submission_test_result')
    op.drop_table('submission_extended_test_result')
    # ### end Alembic commands ###
