"""empty message

Revision ID: 9c5db053ae94
Revises: e71c7341f138
Create Date: 2021-04-29 21:58:33.042179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c5db053ae94'
down_revision = 'e71c7341f138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'nickname',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'nickname',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
