"""empty message

Revision ID: 9f8d78b97aba
Revises: ada4eb80f1c9
Create Date: 2019-11-25 23:24:28.263265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f8d78b97aba'
down_revision = 'ada4eb80f1c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'mat_num',
               existing_type=sa.INTEGER(),
               type_=sa.Float(asdecimal=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'mat_num',
               existing_type=sa.Float(asdecimal=True),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
