"""empty message

Revision ID: a538def48d62
Revises: 6145fb21e678
Create Date: 2019-11-04 12:36:48.910941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a538def48d62'
down_revision = '6145fb21e678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('category', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise', 'category')
    # ### end Alembic commands ###
