"""empty message

Revision ID: afd6d757a15e
Revises: 3c4183d13d38
Create Date: 2019-11-10 19:27:42.679971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afd6d757a15e'
down_revision = '3c4183d13d38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_entry_service', sa.Column('bind_executable', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise_entry_service', 'bind_executable')
    # ### end Alembic commands ###
