"""empty message

Revision ID: fd7bdab619ae
Revises: 9c5db053ae94
Create Date: 2021-04-30 11:26:30.143323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd7bdab619ae'
down_revision = '9c5db053ae94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_ressource_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpu_cnt_max', sa.Float(), nullable=True),
    sa.Column('cpu_shares', sa.Integer(), nullable=True),
    sa.Column('pids_max', sa.Integer(), nullable=True),
    sa.Column('memory_in_mb', sa.Integer(), nullable=True),
    sa.Column('memory_swap_in_mb', sa.Integer(), nullable=True),
    sa.Column('memory_kernel_in_mb', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('exercise_entry_service', sa.Column('ressource_limit_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exercise_entry_service', 'exercise_ressource_limits', ['ressource_limit_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercise_entry_service', type_='foreignkey')
    op.drop_column('exercise_entry_service', 'ressource_limit_id')
    op.drop_table('exercise_ressource_limits')
    # ### end Alembic commands ###
